config/routes.rb
Smarthome::Application.routes.draw do

  resources :groups do
    resources :devices
  end
  
  resources :readings

  resources :devices

     match 'basic_example' => 'basic_example#basic_chart'

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :devices
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  # GET /readings
  # GET /readings.xml
  def index
    @readings = Reading.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @readings }
    end
  end

  # GET /readings/1
  # GET /readings/1.xml
  def show
    @reading = Reading.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reading }
    end
  end

  # GET /readings/new
  # GET /readings/new.xml
  def new
    @reading = Reading.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reading }
    end
  end

  # GET /readings/1/edit
  def edit
    @reading = Reading.find(params[:id])
  end

  # POST /readings
  # POST /readings.xml
  def create
    @reading = Reading.new(params[:reading])

    respond_to do |format|
      if @reading.save
        format.html { redirect_to(@reading, :notice => 'Reading was successfully created.') }
        format.xml  { render :xml => @reading, :status => :created, :location => @reading }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reading.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /readings/1
  # PUT /readings/1.xml
  def update
    @reading = Reading.find(params[:id])

    respond_to do |format|
      if @reading.update_attributes(params[:reading])
        format.html { redirect_to(@reading, :notice => 'Reading was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reading.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.xml
  def destroy
    @reading = Reading.find(params[:id])
    @reading.destroy

    respond_to do |format|
      format.html { redirect_to(readings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/readings/_form.html.erb
<%= form_for(@reading) do |f| %>
  <% if @reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% @reading.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device_id %><br />
    <%= f.text_field :device_id %>
  </div>
  <div class="field">
    <%= f.label :voltage %><br />
    <%= f.text_field :voltage %>
  </div>
  <div class="field">
    <%= f.label :current %><br />
    <%= f.text_field :current %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br />
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readings/edit.html.erb
<h1>Editing reading</h1>

<%= render 'form' %>

<%= link_to 'Show', @reading %> |
<%= link_to 'Back', readings_path %>

app/views/readings/index.html.erb
<h1>Listing readings</h1>

<table>
  <tr>
    <th>Device</th>
    <th>Voltage</th>
    <th>Current</th>
    <th>Timestamp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @readings.each do |reading| %>
  <tr>
    <td><%= reading.device_id %></td>
    <td><%= reading.voltage %></td>
    <td><%= reading.current %></td>
    <td><%= reading.timestamp %></td>
    <td><%= link_to 'Show', reading %></td>
    <td><%= link_to 'Edit', edit_reading_path(reading) %></td>
    <td><%= link_to 'Destroy', reading, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reading', new_reading_path %>

app/views/readings/new.html.erb
<h1>New reading</h1>

<%= render 'form' %>

<%= link_to 'Back', readings_path %>

app/views/readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Device:</b>
  <%= @reading.device_id %>
</p>

<p>
  <b>Voltage:</b>
  <%= @reading.voltage %>
</p>

<p>
  <b>Current:</b>
  <%= @reading.current %>
</p>

<p>
  <b>Timestamp:</b>
  <%= @reading.timestamp %>
</p>


<%= link_to 'Edit', edit_reading_path(@reading) %> |
<%= link_to 'Back', readings_path %>