config/routes.rb
Smarthome::Application.routes.draw do

  resources :groups do
    resources :devices
  end
  
  resources :readings

  resources :devices

     match 'basic_example' => 'basic_example#basic_chart'

end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :readings
  belongs_to :groups
  
  validates :name, :presence => true
  validates :group_id, :presence => true
  
  PRIORITY = ['1','2','3','4','5']
  STATUS = [['Active','Active'],['Non-Active','Non-Active']]
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.xml
  def index
    
    if (params[:group_id])
      @devices = Device.find(:all,:conditions => ["group_id = ?",params[:group_id]])
      @flag = 1
    else
      @devices = Device.all
      @flag = 0
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.xml
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.xml
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.xml
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to(@device, :notice => 'Device was successfully created.') }
        format.xml  { render :xml => @device, :status => :created, :location => @device }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.xml
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to(@device, :notice => 'Device was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.xml
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to(devices_url) }
      format.xml  { head :ok }
    end
  end
  
  def update_priority
    priority = Group.find_all_by_id(params[:device_group_id])
    @html = 'priority'
    render_text "test"
  end
    
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= collection_select :device, :group_id, Group.all, :id, :name %>
  </div>
  
  <div class="field">
    <%= f.label :priority %><br />
    <%= select(:device,:priority,Device::PRIORITY,:selected => 5)  %>
  </div>
  
  <div class="field">
    <%= f.label :status %><br />
    <%= select(:device,:status,Device::STATUS,:selected => 'Active') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %> | 
<%= link_to 'Home', "http://localhost:3000/"%>

app/views/devices/index.html.erb
<h2>Listing devices</h2>
<br/><br/>
<table>
  <tr>
    <th>Name</th>
    <th>Priority</th>
    <th>Group</th>
    <th>Status</th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>
<tr>
    <td><%= device.name %></td>
    <td><%= device.priority %></td>
    <td><%= device.group_id %></td>
    <td><%= device.status %></td>
    <td><%= link_to 'Edit', edit_device_path(device) %></td>
    <td><%= link_to 'Destroy', device, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_device_path %> |
<% if @flag == 1 %>
  <%= link_to 'Back', groups_path%> 
<% end %> |
<%= link_to 'Home', "http://localhost:3000/"%>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %> |
<%= link_to 'Home', "http://localhost:3000/"%>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @device.name %>
</p>

<p>
  <b>Priority:</b>
  <%= @device.priority %>
</p>

<p>
  <b>Group:</b>
  <%= @device.group_id %>
</p>

<p>
  <b>Status:</b>
  <%= @device.status %>
</p>


<%= link_to 'Edit', edit_device_path(@device)  %> |
<%= link_to 'Back', devices_path %> |
<%= link_to 'Home', "http://localhost:3000/"%>